services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: testtemp
      POSTGRES_USER: testtemp
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testtemp -d testtemp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    image: sanjeevthapa363/awseks:latest
    container_name: app
    environment:
#      SPRING_DATASOURCE_URL: jdbc://postgresql://tempo-db.cbaw62oyszb8.us-east-1.rds.amazonaws.com:5432/tempor
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc://postgresql://postgres:5432/testtemp
      SPRING_DATASOURCE_USERNAME: testtemp
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy