name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'corretto'
        cache: maven
        
    - name: Build with Maven
      run: |
        docker compose ls
        mvn -B clean package -DskipTests --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: sanjeevthapa363/awseks:latest

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: sanjeevthapa363/awseks:latest
